[colors.primary]
foreground = "0xdedeef"
background = "0x1a1a1a"

[colors.normal]
black   = "0x1a1a1a"
red     = "0xef3a3a"
green   = "0x3aef3a"
yellow  = "0xd5e600"
blue    = "0x3a3aef"
magenta = "0xdf3adf"
cyan    = "0x3fdaef"
white   = "0xdadada"

[colors.bright]
black   = "0x5a5a5a"
red     = "0xf3aaaa"
green   = "0xaaf3aa"
yellow  = "0xe0f380"
blue    = "0xaaaaf3"
magenta = "0xe5aae5"
cyan    = "0xaae5f3"
white   = "0xf3f3f3"

